### ISSUE TITLE
Got an error following the quick start

### ISSUE THREAD

**Issue by worldspawn** [hendryluk/alpaca#17]
Hi,

using this controller i got the error below.

``` csharp
    [RestController]
    public class TestController
    {
        [Route("hello")]
        public string Hello()
        {
            return "Hello World";
        }
    }
```

``` xml
<Error>
<Message>An error has occurred.</Message>
<ExceptionMessage>
Exception has been thrown by the target of an invocation.
</ExceptionMessage>
<ExceptionType>System.Reflection.TargetInvocationException</ExceptionType>
<StackTrace>
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor) at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments) at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) at Cormo.Impl.Weld.CormoProxyGenerator.ComponentInterceptor.Intercept(IInvocation invocation) at Castle.DynamicProxy.AbstractInvocation.Proceed() at Cormo.Weld.Proxies.TestControllerProxy.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken) at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()
</StackTrace>
<InnerException>
<Message>An error has occurred.</Message>
<ExceptionMessage>
Processing of the HTTP request resulted in an exception. Please see the HTTP response returned by the 'Response' property of this exception for details.
</ExceptionMessage>
<ExceptionType>System.Web.Http.HttpResponseException</ExceptionType>
<StackTrace>
at System.Web.Http.Controllers.ApiControllerActionSelector.ActionSelectorCacheItem.SelectAction(HttpControllerContext controllerContext) at System.Web.Http.Controllers.ApiControllerActionSelector.SelectAction(HttpControllerContext controllerContext) at System.Web.Http.ApiController.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken) --- End of stack trace from previous location where exception was thrown --- at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() at Cormo.Impl.Weld.CormoProxyGenerator.ForwardingInterceptor.Intercept(IInvocation invocation) at Castle.DynamicProxy.AbstractInvocation.Proceed() at Cormo.Weld.Proxies.IHttpControllerProxy.ExecuteAsync(HttpControllerContext controllerContext, CancellationToken cancellationToken)
</StackTrace>
</InnerException>
</Error>
```

**Comment by worldspawn** [comment]
Turns out I need HttpGet on it.
